version: '3.8'

services:
  server:
    container_name: fennec-server
    image: fennec-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./storage:/app/storage
    environment:
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PREFIX=${REDIS_PREFIX}
    restart: unless-stopped
